export const cityData =[
    "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli",
    "Vasai-Virar", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad",
    "Amritsar", "Navi Mumbai", "Allahabad", "Ranchi", "Howrah",
    "Coimbatore", "Jabalpur", "Gwalior", "Vijayawada", "Jodhpur",
    "Madurai", "Raipur", "Kota", "Chandrapur", "Guwahati",
    "Solapur", "Hubli-Dharwad", "Bareilly", "Moradabad", "Mysore",
    "Gurgaon", "Aligarh", "Jalandhar", "Tiruchirappalli", "Bhubaneswar",
    "Salem", "Mira-Bhayandar", "Warangal", "Guntur", "Bhiwandi",
    "Saharanpur", "Gorakhpur", "Bikaner", "Amravati", "Noida",
    "Jamnagar", "Bhilai", "Cuttack", "Firozabad", "Kochi",
    "Nellore", "Bhavnagar", "Dehradun", "Durgapur", "Asansol",
    "Rourkela", "Nanded", "Kolhapur", "Ajmer", "Akola",
    "Gulbarga", "Jamshedpur", "Ujjain", "Loni", "Siliguri",
    "Jhansi", "Ulhasnagar", "Nellore", "Jammu", "Sangli-Miraj & Kupwad",
    "Mangalore", "Erode", "Belgaum", "Ambattur", "Tirunelveli",
    "Malegaon", "Gaya", "Jalgaon", "Udaipur", "Maheshtala",
    "Davanagere", "Kozhikode", "Kurnool", "Rajpur Sonarpur", "Rajahmundry",
    "Bokaro Steel City", "South Dumdum", "Bellary", "Patiala", "Amaravati",
    "Bhagalpur", "Avadi", "Tirupati", "Ichalkaranji", "Kollam",
    "Kadapa", "Kamarhati", "Bilaspur", "Shahjahanpur", "Satara",
    "Bijapur", "Rampur", "Shivamogga", "Chandrapur", "Junagadh",
    "Thrissur", "Alwar", "Bardhaman", "Kulti", "Kakinada",
    "Nizamabad", "Parbhani", "Tumkur", "Khammam", "Ozhukarai",
    "Bihar Sharif", "Panipat", "Darbhanga", "Bally", "Aizawl",
    "Dewas", "Ichalkaranji", "Karnal", "Bathinda", "Jalna",
    "Eluru", "Kirari Suleman Nagar", "Barasat", "Purnia", "Satna",
    "Mau", "Sonipat", "Farrukhabad", "Durg", "Imphal",
    "Ratlam", "Hapur", "Arrah", "Karimnagar", "Anantapur",
    "Etawah", "Ambernath", "North Dumdum", "Bharatpur", "Begusarai",
    "New Delhi", "Gandhinagar", "Baranagar", "Tiruvottiyur", "Puducherry",
    "Sikar", "Thoothukudi", "Rewa", "Mirzapur", "Raichur",
    "Pali", "Ramagundam", "Haridwar", "Vijayanagaram", "Katihar",
    "Nagarcoil", "Sri Ganganagar", "Karawal Nagar", "Mango", "Thanjavur",
    "Bulandshahr", "Uluberia", "Murwara (Katni)", "Sambalpur", "Singrauli",
    "Nadiad", "Secunderabad", "Kottayam", "Korba", "Rampur",
    "Shimoga", "Rae Bareli", "Agartala",
    // Continue the list...
  ]
  